name: Run git diff

on:
  push:
    branches:
      - master

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
      #- name: Setup Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.11.2'    
      - name: Show Modified Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
          cat modified_files.txt
          echo "::set-output name=MODIFIED_FILES::$(cat modified_files.txt)"

      - name: Use Modified Files in Subsequent Steps
        run: |
          echo "Modified Files: $MODIFIED_FILES"
          
#echo "$(git diff --stat --cached origin/master)"