name: Pre-push Check

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  pre-push-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: |
          pwd
          chmod +x ./pre-push.py
          ./pre-push.py
          exit_code=$?

          if [ $exit_code -eq 0 ]; then
            echo "Pre-push check passed. Integration allowed."
            # Continue with your regular build and test steps here
          else
            echo "Pre-push check failed. Integration blocked."
            exit 1
          fi
