name: Pre-push Check

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  pre-push-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master  # Adjust the branch name as needed

      - name: Set Working Directory
        run: cd $GITHUB_WORKSPACE
        
      - name: Make Script Executable
        run: chmod +x pre-push.py

      - name: Run Python Script
        id: script
        run: |
          ./pre-push.py
          echo "EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Check Exit Code
        run: exit ${{ env.EXIT_CODE }}
